rm -rf .//ch10_enums_and_patterns/.git
rm -rf .//ch06_expressions/.git
rm -rf .//ch01/.git
rm -rf .//ch07_errors/.git
rm -rf .//ch13_utility_traits/.git
rm -rf .//ch23_foreign_functions/.git
rm -rf .//ch12_overloading/.git
rm -rf .//prog-rust-2nd-ws/.git
rm -rf .//ch08_crates_modules/.git
rm -rf .//ch19_concurrency/.git
rm -rf .//ch21_macros/.git
rm -rf .//ch22_unsafe_code/.git
rm -rf .//ch16_collections/.git
rm -rf .//ch04_ownership/.git
rm -rf .//ch11_traits_and_generics/.git
rm -rf .//ch17_strings/.git
rm -rf .//ch09_structs/.git
rm -rf .//ch02/.git
rm -rf .//ch03_fundamentals/.git
rm -rf .//ch18_io/.git
rm -rf .//build_server/.git
rm -rf .//ch15_iterators/.git
rm -rf .//ch20_async/.git
rm -rf .//ch14_closures/.git
rm -rf .//ch05_references/.git
 